<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>Jacana.Reporting.Infrastructure</AssemblyName>
    <RootNamespace>Jacana.Reporting.Infrastructure</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Dapper" Version="2.1.35" />
    <PackageReference Include="Npgsql" Version="8.0.6" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Reporting.Application\Reporting.Application.csproj" />
  </ItemGroup>
</Project>
