<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>Jacana.HRMS.DbInitializer</AssemblyName>
    <RootNamespace>Jacana.HRMS.DbInitializer</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\SharedKernel\SharedKernel.Infrastructure\SharedKernel.Infrastructure.csproj" />
    <ProjectReference Include="..\..\src\Modules\Identity\Identity.Infrastructure\Identity.Infrastructure.csproj" />
    <ProjectReference Include="..\..\src\Modules\PatientRegistration\PatientRegistration.Infrastructure\PatientRegistration.Infrastructure.csproj" />
    <ProjectReference Include="..\..\src\Modules\Clinical\Clinical.Infrastructure\Clinical.Infrastructure.csproj" />
    <ProjectReference Include="..\..\src\Modules\Inventory\Inventory.Infrastructure\Inventory.Infrastructure.csproj" />
    <ProjectReference Include="..\..\src\Modules\Pharmacy\Pharmacy.Infrastructure\Pharmacy.Infrastructure.csproj" />
    <ProjectReference Include="..\..\src\Modules\Laboratory\Laboratory.Infrastructure\Laboratory.Infrastructure.csproj" />
    <ProjectReference Include="..\..\src\Modules\Billing\Billing.Infrastructure\Billing.Infrastructure.csproj" />
    <ProjectReference Include="..\..\src\Modules\Inpatient\Inpatient.Infrastructure\Inpatient.Infrastructure.csproj" />
    <ProjectReference Include="..\..\src\Modules\Notifications\Notifications.Infrastructure\Notifications.Infrastructure.csproj" />
    <ProjectReference Include="..\..\src\Modules\Audit\Audit.Infrastructure\Audit.Infrastructure.csproj" />
  </ItemGroup>
</Project>
